baseURL = "https://kw-lee.github.io"
title = "KWLee's Blog"

# for smart copyright line, leave this blank and check [params.copyright]
# copyright = ""

theme = "hugo-hello-programmer-theme"

disqusShortname = ""
googleAnalytics = ""

Paginate = 7
# preserveTaxonomyNames = true

# enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true
enableEmoji = true

# Missing translations will default to this content language
DefaultContentLanguage = "en"

[author]
	name = "kw-lee"
	email = "kwlee1718@gmail.com"

[params]
	description = "Home"

# [taxonomies]
# 	category = "categories"
# 	tag = "tags"
# 	subcategory = "subcategories"

# favicon = "favicon.ico"
# customCSS = ["css/custom.css"]
# customJS = ["js/custom.js"]
# gopher = "" # used in 404 template ( Generator: https://gopherize.me )

summaryLength = 30